blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Condition00/debateroom-ai/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/Condition00/debateroom-ai/security/advisories/new
    about: Report a security vulnerability privately
